import React, { createContext, useContext, useState, ReactNode, useEffect } from 'react';

export type Language = 'it' | 'en' | 'fr' | 'de' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  it: {
    // Navigation
    'nav.home': 'Home',
    'nav.virtualExploration': 'Virtual Exploration',
    'nav.places': 'Luoghi',
    'nav.blog': 'Blog',
    'nav.addPlace': 'Inserisci luogo',
    
    // Home
    'home.title': 'explore',
    'home.subtitle': 'Independent local guide',
    'home.login': 'Accedi',
    'home.register': 'Registrati',
    'home.about': 'Chi siamo?',
    'home.settings': 'Impostazioni',
    'home.selectCity': 'Seleziona città',
    'home.selectLanguage': 'Seleziona lingua',
    'home.allCities': 'Tutte le città',
    'home.virtualExploration': 'Virtual exploration',
    'home.virtualExplorationDesc': 'Esplora luoghi sulla mappa',
    'home.places': 'Luoghi',
    'home.placesDesc': 'Scopri tutti i luoghi',
    'home.blogTitle': 'Blog',
    'home.blogDesc': 'Articoli e guide',
    'home.travellerPath': 'Traveller.Path',
    'home.travellerPathDesc': 'Itinerari personalizzati',
    'home.travellerPathPending': 'Questionario in sospeso',
    'home.finishSurvey': 'Clicca per finire il questionario!',
    'home.whichCity': 'Which city will next?',
    'home.stayTuned': 'Stay tuned my friends',
    'home.workInProgress': 'In corso',
    
    // Blog
    'blog.title': 'blog',
    'blog.subtitle': 'Guide, consigli e storie di viaggio',
    'blog.writeArticle': 'Scrivi articolo',
    'blog.searchArticles': 'Cerca articoli...',
    'blog.filters': 'Filtri',
    'blog.faq': 'FAQ',
    'blog.dayTrip': 'Day Trip',
    'blog.tips': 'Tips',
    'blog.faqTitle': 'Domande frequenti',
    'blog.faqDesc': 'Risposte alle domande più comuni sulla piattaforma',
    'blog.dayTripTitle': 'Itinerari giornalieri',
    'blog.dayTripDesc': 'Scopri i migliori itinerari per gite di un giorno',
    'blog.tipsTitle': 'Consigli di viaggio',
    'blog.tipsDesc': 'Suggerimenti utili per migliorare la tua esperienza di viaggio',
    'blog.read': 'Leggi',
    
    // Virtual Exploration
    'virtual.title': 'virtual exploration',
    'virtual.subtitle': 'Esplora luoghi sulla mappa interattiva',
    'virtual.favorites': 'I tuoi luoghi preferiti',
    'virtual.noFavorites': 'Nessun luogo preferito ancora.',
    'virtual.visit': 'Visita',
    'virtual.googleMap': 'Google Map',
    'virtual.categories': 'Categorie',
    'virtual.all': 'Tutte',
    'virtual.clearFilters': 'Cancella filtri',
    'virtual.addPlace': 'Aggiungi luogo',
    'virtual.enlarge': 'Ingrandisci',
    'virtual.close': 'Chiudi',
    'virtual.noFavoritesDesc': 'Clicca sul cuore sulla mappa per aggiungere luoghi ai tuoi preferiti',
    'virtual.removeFavorite': 'Rimuovi dai preferiti',
    'virtual.exploreSubtitle': 'Esplora i luoghi sulla mappa e salva i tuoi preferiti',
    
    // Places (Luoghi)
    'places.title': 'Luoghi',
    'places.subtitle': 'Scopri tutti i luoghi selezionati con cura dalla nostra guida',
    'places.approved': 'Explore Approved',
    'places.search': 'Cerca luoghi...',
    'places.all': 'Tutte',
    'places.noResults': 'Nessun luogo trovato',
    'places.noResultsDesc': 'Prova a modificare i filtri di ricerca',
    'places.loading': 'Caricamento...',
    'places.cuisine': 'Tipo di cucina:',
    'places.meat': 'Carne',
    'places.fish': 'Pesce',
    'places.enter': 'Entra',
    'places.maps': 'Maps',
    
    // Traveller Path
    'traveller.title': 'Traveller.Path',
    'traveller.subtitle': 'Crea il tuo itinerario personalizzato',
    'traveller.backHome': 'Torna alla home',
    'traveller.continuing': 'Stai continuando il questionario da dove avevi lasciato',
    'traveller.completed': 'domande completate',
    'traveller.progress': 'Progresso',
    'traveller.previous': 'Precedente',
    'traveller.skip': 'Salta',
    'traveller.next': 'Successiva',
    'traveller.complete': 'Completa',
    'traveller.completedMessage': 'Questionario completato! I tuoi dati sono stati salvati.',
    'traveller.loading': 'Caricamento...',
    
    // Questions
    'question.profileType': 'Sei un Local o un Traveler?',
    'question.gender': 'Genere',
    'question.age': 'Età',
    'question.nationality': 'Nazionalità',
    'question.travelComposition': 'Composizione',
    'question.travelInclination': 'Inclinazione',
    'question.duration': 'Tempo di permanenza',
    'question.transport': 'Mezzo di trasporto',
    'question.cuisine': 'Preferenze culinarie',
    'question.accommodationZone': 'Zona di pernottamento',
    'question.accessibility': 'Necessità specifiche',
    
    // Categories
    'category.profile': 'Profilo',
    'category.travel': 'Composizione del viaggio',
    'category.viaggio': 'Viaggio',
    'category.cucina': 'Cucina / preferenze culinarie',
    'category.alloggio': 'Alloggio',
    'category.accessibilità': 'Accessibilità / categorie fragili',
    
    // Options
    'option.local': 'Local',
    'option.traveler': 'Traveler',
    'option.male': 'Maschio',
    'option.female': 'Femmina',
    'option.other': 'Altro',
    'option.under18': '<18',
    'option.1824': '18–24',
    'option.2534': '25–34',
    'option.3549': '35–49',
    'option.5064': '50–64',
    'option.over65': '>65',
    'option.europe': 'Europa',
    'option.usa': 'USA',
    'option.southAmerica': 'Sud America',
    'option.asia': 'Asia',
    'option.africa': 'Africa',
    'option.solo': 'Solo',
    'option.couple': 'Coppia',
    'option.group': 'Gruppo',
    'option.family': 'Famiglia',
    'option.adventure': 'Avventura',
    'option.relax': 'Relax',
    'option.culture': 'Cultura',
    'option.shopping': 'Shopping',
    'option.nightlife': 'Nightlife',
    'option.socializing': 'Socializing',
    'option.1Day': '1 giorno',
    'option.2Days': '2 giorni',
    'option.37Days': '3–7 giorni',
    'option.over7Days': '>7 giorni',
    'option.own': 'Proprio',
    'option.none': 'No',
    'option.rental': 'Vorrei noleggiarlo',
    'option.homemade': 'Casereccia',
    'option.fineDining': 'Fine dining',
    'option.healthy': 'Healthy',
    'option.winePairing': 'Wine pairing',
    'option.streetFood': 'Street food',
    'option.organic': 'Organic',
    'option.dairyFree': 'Dairy free',
    'option.halal': 'Halal',
    'option.nutsFree': 'Nuts free',
    'option.glutenFree': 'Gluten free',
    'option.vegan': 'Vegano',
    'option.vegetarian': 'Vegetariano',
    'option.z1': 'Z1',
    'option.z2': 'Z2',
    'option.z3': 'Z3',
    'option.z4': 'Z4',
    'option.z5': 'Z5',
    'option.reducedMobility': 'Mobilità ridotta',
    'option.elderly': 'Anziani',
    'option.pregnant': 'Donne incinta',
    'option.odorophobia': 'Odorofobia',
    'option.mentalWellness': 'Benessere mentale'
  },
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.virtualExploration': 'Virtual Exploration',
    'nav.places': 'Places',
    'nav.blog': 'Blog',
    'nav.addPlace': 'Add Place',
    
    // Home
    'home.title': 'explore',
    'home.subtitle': 'Independent local guide',
    'home.login': 'Login',
    'home.register': 'Register',
    'home.about': 'About Us?',
    'home.settings': 'Settings',
    'home.selectCity': 'Select city',
    'home.selectLanguage': 'Select language',
    'home.allCities': 'All cities',
    'home.virtualExploration': 'Virtual exploration',
    'home.virtualExplorationDesc': 'Explore places on the map',
    'home.places': 'Places',
    'home.placesDesc': 'Discover all places',
    'home.blogTitle': 'Blog',
    'home.blogDesc': 'Articles and guides',
    'home.travellerPath': 'Traveller.Path',
    'home.travellerPathDesc': 'Personalized itineraries',
    'home.travellerPathPending': 'Pending questionnaire',
    'home.finishSurvey': 'Click to finish the questionnaire!',
    'home.whichCity': 'Which city will next?',
    'home.stayTuned': 'Stay tuned my friends',
    'home.workInProgress': 'In progress',
    
    // Blog
    'blog.title': 'blog',
    'blog.subtitle': 'Guides, tips and travel stories',
    'blog.writeArticle': 'Write article',
    'blog.searchArticles': 'Search articles...',
    'blog.filters': 'Filters',
    'blog.faq': 'FAQ',
    'blog.dayTrip': 'Day Trip',
    'blog.tips': 'Tips',
    'blog.faqTitle': 'Frequently Asked Questions',
    'blog.faqDesc': 'Answers to the most common questions about the platform',
    'blog.dayTripTitle': 'Daily itineraries',
    'blog.dayTripDesc': 'Discover the best itineraries for day trips',
    'blog.tipsTitle': 'Travel tips',
    'blog.tipsDesc': 'Useful suggestions to improve your travel experience',
    'blog.read': 'Read',
    
    // Virtual Exploration
    'virtual.title': 'virtual exploration',
    'virtual.subtitle': 'Explore places on the interactive map',
    'virtual.favorites': 'Your favorite places',
    'virtual.noFavorites': 'No favorite places yet.',
    'virtual.visit': 'Visit',
    'virtual.googleMap': 'Google Map',
    'virtual.categories': 'Categories',
    'virtual.all': 'All',
    'virtual.clearFilters': 'Clear filters',
    'virtual.addPlace': 'Add place',
    'virtual.enlarge': 'Enlarge',
    'virtual.close': 'Close',
    'virtual.noFavoritesDesc': 'Click the heart on the map to add places to your favorites',
    'virtual.removeFavorite': 'Remove from favorites',
    'virtual.exploreSubtitle': 'Explore places on the map and save your favorites',
    
    // Places (Luoghi)
    'places.title': 'Places',
    'places.subtitle': 'Discover all places carefully selected by our guide',
    'places.approved': 'Explore Approved',
    'places.search': 'Search places...',
    'places.all': 'All',
    'places.noResults': 'No places found',
    'places.noResultsDesc': 'Try modifying the search filters',
    'places.loading': 'Loading...',
    'places.cuisine': 'Cuisine type:',
    'places.meat': 'Meat',
    'places.fish': 'Fish',
    'places.enter': 'Enter',
    'places.maps': 'Maps',
    
    // Traveller Path
    'traveller.title': 'Traveller.Path',
    'traveller.subtitle': 'Create your personalized itinerary',
    'traveller.backHome': 'Back to home',
    'traveller.continuing': 'You are continuing the questionnaire from where you left off',
    'traveller.completed': 'questions completed',
    'traveller.progress': 'Progress',
    'traveller.previous': 'Previous',
    'traveller.skip': 'Skip',
    'traveller.next': 'Next',
    'traveller.complete': 'Complete',
    'traveller.completedMessage': 'Questionnaire completed! Your data has been saved.',
    'traveller.loading': 'Loading...',
    
    // Questions
    'question.profileType': 'Are you a Local or a Traveler?',
    'question.gender': 'Gender',
    'question.age': 'Age',
    'question.nationality': 'Nationality',
    'question.travelComposition': 'Composition',
    'question.travelInclination': 'Inclination',
    'question.duration': 'Duration of stay',
    'question.transport': 'Means of transport',
    'question.cuisine': 'Culinary preferences',
    'question.accommodationZone': 'Accommodation zone',
    'question.accessibility': 'Specific needs',
    
    // Categories
    'category.profile': 'Profile',
    'category.travelComposition': 'Travel composition',
    'category.travel': 'Travel',
    'category.cuisine': 'Cuisine / culinary preferences',
    'category.accommodation': 'Accommodation',
    'category.accessibility': 'Accessibility / fragile categories',
    
    // Options
    'option.local': 'Local',
    'option.traveler': 'Traveler',
    'option.male': 'Male',
    'option.female': 'Female',
    'option.other': 'Other',
    'option.under18': '<18',
    'option.18-24': '18–24',
    'option.25-34': '25–34',
    'option.35-49': '35–49',
    'option.50-64': '50–64',
    'option.over65': '>65',
    'option.europe': 'Europe',
    'option.usa': 'USA',
    'option.southAmerica': 'South America',
    'option.asia': 'Asia',
    'option.africa': 'Africa',
    'option.solo': 'Solo',
    'option.couple': 'Couple',
    'option.group': 'Group',
    'option.family': 'Family',
    'option.adventure': 'Adventure',
    'option.relax': 'Relax',
    'option.culture': 'Culture',
    'option.shopping': 'Shopping',
    'option.nightlife': 'Nightlife',
    'option.socializing': 'Socializing',
    'option.1day': '1 day',
    'option.2days': '2 days',
    'option.3-7days': '3–7 days',
    'option.over7days': '>7 days',
    'option.own': 'Own',
    'option.none': 'No',
    'option.rental': 'Would like to rent',
    'option.homemade': 'Homemade',
    'option.fineDining': 'Fine dining',
    'option.healthy': 'Healthy',
    'option.winePairing': 'Wine pairing',
    'option.streetFood': 'Street food',
    'option.organic': 'Organic',
    'option.dairyFree': 'Dairy free',
    'option.halal': 'Halal',
    'option.nutsFree': 'Nuts free',
    'option.glutenFree': 'Gluten free',
    'option.vegan': 'Vegan',
    'option.vegetarian': 'Vegetarian',
    'option.z1': 'Z1',
    'option.z2': 'Z2',
    'option.z3': 'Z3',
    'option.z4': 'Z4',
    'option.z5': 'Z5',
    'option.reducedMobility': 'Reduced mobility',
    'option.elderly': 'Elderly',
    'option.pregnant': 'Pregnant women',
    'option.odorophobia': 'Odorophobia',
    'option.mentalWellness': 'Mental wellness'
  },
  fr: {
    // Navigation
    'nav.home': 'Accueil',
    'nav.virtualExploration': 'Exploration Virtuelle',
    'nav.places': 'Lieux',
    'nav.blog': 'Blog',
    'nav.addPlace': 'Ajouter lieu',
    
    // Home
    'home.title': 'explorer',
    'home.subtitle': 'Guide local indépendant',
    'home.login': 'Connexion',
    'home.register': 'S\'inscrire',
    'home.about': 'Qui sommes-nous?',
    'home.settings': 'Paramètres',
    'home.selectCity': 'Sélectionner ville',
    'home.selectLanguage': 'Sélectionner langue',
    'home.allCities': 'Toutes les villes',
    'home.virtualExploration': 'Exploration virtuelle',
    'home.virtualExplorationDesc': 'Explorez les lieux sur la carte',
    'home.places': 'Lieux',
    'home.placesDesc': 'Découvrez tous les lieux',
    'home.blogTitle': 'Blog',
    'home.blogDesc': 'Articles et guides',
    'home.travellerPath': 'Traveller.Path',
    'home.travellerPathDesc': 'Itinéraires personnalisés',
    'home.travellerPathPending': 'Questionnaire en attente',
    'home.finishSurvey': 'Cliquez pour terminer le questionnaire!',
    'home.whichCity': 'Quelle ville sera la prochaine?',
    'home.stayTuned': 'Restez à l\'écoute mes amis',
    'home.workInProgress': 'En cours',
    
    // Blog
    'blog.title': 'blog',
    'blog.subtitle': 'Guides, conseils et histoires de voyage',
    'blog.writeArticle': 'Écrire article',
    'blog.searchArticles': 'Rechercher articles...',
    'blog.filters': 'Filtres',
    'blog.faq': 'FAQ',
    'blog.dayTrip': 'Excursion',
    'blog.tips': 'Conseils',
    'blog.faqTitle': 'Questions fréquentes',
    'blog.faqDesc': 'Réponses aux questions les plus courantes sur la plateforme',
    'blog.dayTripTitle': 'Itinéraires journaliers',
    'blog.dayTripDesc': 'Découvrez les meilleurs itinéraires pour des excursions d\'une journée',
    'blog.tipsTitle': 'Conseils de voyage',
    'blog.tipsDesc': 'Suggestions utiles pour améliorer votre expérience de voyage',
    'blog.read': 'Lire',
    
    // Virtual Exploration
    'virtual.title': 'exploration virtuelle',
    'virtual.subtitle': 'Explorez les lieux sur la carte interactive',
    'virtual.favorites': 'Vos lieux favoris',
    'virtual.noFavorites': 'Aucun lieu favori pour le moment.',
    'virtual.visit': 'Visiter',
    'virtual.googleMap': 'Google Map',
    'virtual.categories': 'Catégories',
    'virtual.all': 'Toutes',
    'virtual.clearFilters': 'Effacer filtres',
    'virtual.addPlace': 'Ajouter lieu',
    'virtual.enlarge': 'Agrandir',
    'virtual.close': 'Fermer',
    'virtual.noFavoritesDesc': 'Cliquez sur le cœur sur la carte pour ajouter des lieux à vos favoris',
    'virtual.removeFavorite': 'Supprimer des favoris',
    'virtual.exploreSubtitle': 'Explorez les lieux sur la carte et sauvegardez vos favoris',
    
    // Places (Luoghi)
    'places.title': 'Lieux',
    'places.subtitle': 'Découvrez tous les lieux soigneusement sélectionnés par notre guide',
    'places.approved': 'Explore Approuvé',
    'places.search': 'Rechercher lieux...',
    'places.all': 'Toutes',
    'places.noResults': 'Aucun lieu trouvé',
    'places.noResultsDesc': 'Essayez de modifier les filtres de recherche',
    'places.loading': 'Chargement...',
    'places.cuisine': 'Type de cuisine:',
    'places.meat': 'Viande',
    'places.fish': 'Poisson',
    'places.enter': 'Entrer',
    'places.maps': 'Maps',
    
    // Traveller Path
    'traveller.title': 'Traveller.Path',
    'traveller.subtitle': 'Créez votre itinéraire personnalisé',
    'traveller.backHome': 'Retour à l\'accueil',
    'traveller.continuing': 'Vous continuez le questionnaire où vous l\'avez laissé',
    'traveller.completed': 'questions complétées',
    'traveller.progress': 'Progrès',
    'traveller.previous': 'Précédent',
    'traveller.skip': 'Passer',
    'traveller.next': 'Suivant',
    'traveller.complete': 'Terminer',
    'traveller.completedMessage': 'Questionnaire terminé! Vos données ont été sauvegardées.',
    'traveller.loading': 'Chargement...',
    
    // Questions
    'question.profileType': 'Êtes-vous un Local ou un Voyageur?',
    'question.gender': 'Genre',
    'question.age': 'Âge',
    'question.nationality': 'Nationalité',
    'question.travelComposition': 'Composition',
    'question.travelInclination': 'Inclination',
    'question.duration': 'Durée du séjour',
    'question.transport': 'Moyen de transport',
    'question.cuisine': 'Préférences culinaires',
    'question.accommodationZone': 'Zone d\'hébergement',
    'question.accessibility': 'Besoins spécifiques',
    
    // Categories
    'category.profile': 'Profil',
    'category.travelComposition': 'Composition du voyage',
    'category.travel': 'Voyage',
    'category.cuisine': 'Cuisine / préférences culinaires',
    'category.accommodation': 'Hébergement',
    'category.accessibility': 'Accessibilité / catégories fragiles',
    
    // Options
    'option.local': 'Local',
    'option.traveler': 'Voyageur',
    'option.male': 'Homme',
    'option.female': 'Femme',
    'option.other': 'Autre',
    'option.under18': '<18',
    'option.18-24': '18–24',
    'option.25-34': '25–34',
    'option.35-49': '35–49',
    'option.50-64': '50–64',
    'option.over65': '>65',
    'option.europe': 'Europe',
    'option.usa': 'USA',
    'option.southAmerica': 'Amérique du Sud',
    'option.asia': 'Asie',
    'option.africa': 'Afrique',
    'option.solo': 'Seul',
    'option.couple': 'Couple',
    'option.group': 'Groupe',
    'option.family': 'Famille',
    'option.adventure': 'Aventure',
    'option.relax': 'Détente',
    'option.culture': 'Culture',
    'option.shopping': 'Shopping',
    'option.nightlife': 'Vie nocturne',
    'option.socializing': 'Socialisation',
    'option.1day': '1 jour',
    'option.2days': '2 jours',
    'option.3-7days': '3–7 jours',
    'option.over7days': '>7 jours',
    'option.own': 'Propre',
    'option.none': 'Non',
    'option.rental': 'Voudrait louer',
    'option.homemade': 'Fait maison',
    'option.fineDining': 'Gastronomie',
    'option.healthy': 'Sain',
    'option.winePairing': 'Accord vin',
    'option.streetFood': 'Street food',
    'option.organic': 'Bio',
    'option.dairyFree': 'Sans produits laitiers',
    'option.halal': 'Halal',
    'option.nutsFree': 'Sans noix',
    'option.glutenFree': 'Sans gluten',
    'option.vegan': 'Végan',
    'option.vegetarian': 'Végétarien',
    'option.z1': 'Z1',
    'option.z2': 'Z2',
    'option.z3': 'Z3',
    'option.z4': 'Z4',
    'option.z5': 'Z5',
    'option.reducedMobility': 'Mobilité réduite',
    'option.elderly': 'Personnes âgées',
    'option.pregnant': 'Femmes enceintes',
    'option.odorophobia': 'Odorophobie',
    'option.mentalWellness': 'Bien-être mental'
  },
  de: {
    // Navigation
    'nav.home': 'Startseite',
    'nav.virtualExploration': 'Virtuelle Erkundung',
    'nav.places': 'Orte',
    'nav.blog': 'Blog',
    'nav.addPlace': 'Ort hinzufügen',
    
    // Home
    'home.title': 'erkunden',
    'home.subtitle': 'Unabhängiger lokaler Führer',
    'home.login': 'Anmelden',
    'home.register': 'Registrieren',
    'home.about': 'Wer sind wir?',
    'home.settings': 'Einstellungen',
    'home.selectCity': 'Stadt wählen',
    'home.selectLanguage': 'Sprache wählen',
    'home.allCities': 'Alle Städte',
    'home.virtualExploration': 'Virtuelle Erkundung',
    'home.virtualExplorationDesc': 'Orte auf der Karte erkunden',
    'home.places': 'Orte',
    'home.placesDesc': 'Alle Orte entdecken',
    'home.blogTitle': 'Blog',
    'home.blogDesc': 'Artikel und Leitfäden',
    'home.travellerPath': 'Traveller.Path',
    'home.travellerPathDesc': 'Personalisierte Routen',
    'home.travellerPathPending': 'Ausstehender Fragebogen',
    'home.finishSurvey': 'Klicken Sie, um den Fragebogen zu beenden!',
    'home.whichCity': 'Welche Stadt wird als nächstes kommen?',
    'home.stayTuned': 'Bleibt dran, meine Freunde',
    'home.workInProgress': 'In Bearbeitung',
    
    // Blog
    'blog.title': 'blog',
    'blog.subtitle': 'Leitfäden, Tipps und Reisegeschichten',
    'blog.writeArticle': 'Artikel schreiben',
    'blog.searchArticles': 'Artikel suchen...',
    'blog.filters': 'Filter',
    'blog.faq': 'FAQ',
    'blog.dayTrip': 'Tagesausflug',
    'blog.tips': 'Tipps',
    'blog.faqTitle': 'Häufig gestellte Fragen',
    'blog.faqDesc': 'Antworten auf die häufigsten Fragen zur Plattform',
    'blog.dayTripTitle': 'Tagesrouten',
    'blog.dayTripDesc': 'Entdecken Sie die besten Routen für Tagesausflüge',
    'blog.tipsTitle': 'Reisetipps',
    'blog.tipsDesc': 'Nützliche Vorschläge zur Verbesserung Ihrer Reiseerfahrung',
    'blog.read': 'Lesen',
    
    // Virtual Exploration
    'virtual.title': 'virtuelle erkundung',
    'virtual.subtitle': 'Orte auf der interaktiven Karte erkunden',
    'virtual.favorites': 'Ihre Lieblingsorte',
    'virtual.noFavorites': 'Noch keine Lieblingsorte.',
    'virtual.visit': 'Besuchen',
    'virtual.googleMap': 'Google Map',
    'virtual.categories': 'Kategorien',
    'virtual.all': 'Alle',
    'virtual.clearFilters': 'Filter löschen',
    'virtual.addPlace': 'Ort hinzufügen',
    'virtual.enlarge': 'Vergrößern',
    'virtual.close': 'Schließen',
    'virtual.noFavoritesDesc': 'Klicken Sie auf das Herz auf der Karte, um Orte zu Ihren Favoriten hinzuzufügen',
    'virtual.removeFavorite': 'Aus Favoriten entfernen',
    'virtual.exploreSubtitle': 'Orte auf der Karte erkunden und Ihre Favoriten speichern',
    
    // Places (Luoghi)
    'places.title': 'Orte',
    'places.subtitle': 'Entdecken Sie alle sorgfältig ausgewählten Orte unseres Leitfadens',
    'places.approved': 'Explore Genehmigt',
    'places.search': 'Orte suchen...',
    'places.all': 'Alle',
    'places.noResults': 'Keine Orte gefunden',
    'places.noResultsDesc': 'Versuchen Sie, die Suchfilter zu ändern',
    'places.loading': 'Laden...',
    'places.cuisine': 'Küchenart:',
    'places.meat': 'Fleisch',
    'places.fish': 'Fisch',
    'places.enter': 'Eingeben',
    'places.maps': 'Maps',
    
    // Traveller Path
    'traveller.title': 'Traveller.Path',
    'traveller.subtitle': 'Erstellen Sie Ihre personalisierte Route',
    'traveller.backHome': 'Zurück zur Startseite',
    'traveller.continuing': 'Sie setzen den Fragebogen fort, wo Sie aufgehört haben',
    'traveller.completed': 'Fragen beantwortet',
    'traveller.progress': 'Fortschritt',
    'traveller.previous': 'Vorherige',
    'traveller.skip': 'Überspringen',
    'traveller.next': 'Nächste',
    'traveller.complete': 'Abschließen',
    'traveller.completedMessage': 'Fragebogen abgeschlossen! Ihre Daten wurden gespeichert.',
    'traveller.loading': 'Laden...',
    
    // Questions
    'question.profileType': 'Sind Sie ein Einheimischer oder ein Reisender?',
    'question.gender': 'Geschlecht',
    'question.age': 'Alter',
    'question.nationality': 'Nationalität',
    'question.travelComposition': 'Zusammensetzung',
    'question.travelInclination': 'Neigung',
    'question.duration': 'Aufenthaltsdauer',
    'question.transport': 'Transportmittel',
    'question.cuisine': 'Kulinarische Vorlieben',
    'question.accommodationZone': 'Unterkunftszone',
    'question.accessibility': 'Spezifische Bedürfnisse',
    
    // Categories
    'category.profile': 'Profil',
    'category.travelComposition': 'Reisezusammensetzung',
    'category.travel': 'Reise',
    'category.cuisine': 'Küche / kulinarische Vorlieben',
    'category.accommodation': 'Unterkunft',
    'category.accessibility': 'Barrierefreiheit / vulnerable Kategorien',
    
    // Options
    'option.local': 'Einheimischer',
    'option.traveler': 'Reisender',
    'option.male': 'Männlich',
    'option.female': 'Weiblich',
    'option.other': 'Andere',
    'option.under18': '<18',
    'option.18-24': '18–24',
    'option.25-34': '25–34',
    'option.35-49': '35–49',
    'option.50-64': '50–64',
    'option.over65': '>65',
    'option.europe': 'Europa',
    'option.usa': 'USA',
    'option.southAmerica': 'Südamerika',
    'option.asia': 'Asien',
    'option.africa': 'Afrika',
    'option.solo': 'Alleine',
    'option.couple': 'Paar',
    'option.group': 'Gruppe',
    'option.family': 'Familie',
    'option.adventure': 'Abenteuer',
    'option.relax': 'Entspannung',
    'option.culture': 'Kultur',
    'option.shopping': 'Einkaufen',
    'option.nightlife': 'Nachtleben',
    'option.socializing': 'Geselligkeit',
    'option.1day': '1 Tag',
    'option.2days': '2 Tage',
    'option.3-7days': '3–7 Tage',
    'option.over7days': '>7 Tage',
    'option.own': 'Eigenes',
    'option.none': 'Nein',
    'option.rental': 'Möchte mieten',
    'option.homemade': 'Hausgemacht',
    'option.fineDining': 'Gehobene Küche',
    'option.healthy': 'Gesund',
    'option.winePairing': 'Weinpaarung',
    'option.streetFood': 'Street Food',
    'option.organic': 'Bio',
    'option.dairyFree': 'Milchfrei',
    'option.halal': 'Halal',
    'option.nutsFree': 'Nussfrei',
    'option.glutenFree': 'Glutenfrei',
    'option.vegan': 'Vegan',
    'option.vegetarian': 'Vegetarisch',
    'option.z1': 'Z1',
    'option.z2': 'Z2',
    'option.z3': 'Z3',
    'option.z4': 'Z4',
    'option.z5': 'Z5',
    'option.reducedMobility': 'Eingeschränkte Mobilität',
    'option.elderly': 'Ältere Menschen',
    'option.pregnant': 'Schwangere Frauen',
    'option.odorophobia': 'Odorophobie',
    'option.mentalWellness': 'Geistiges Wohlbefinden'
  },
  es: {
    // Navigation
    'nav.home': 'Inicio',
    'nav.virtualExploration': 'Exploración Virtual',
    'nav.places': 'Lugares',
    'nav.blog': 'Blog',
    'nav.addPlace': 'Añadir lugar',
    
    // Home
    'home.title': 'explorar',
    'home.subtitle': 'Guía local independiente',
    'home.login': 'Iniciar sesión',
    'home.register': 'Registrarse',
    'home.about': '¿Quiénes somos?',
    'home.settings': 'Configuración',
    'home.selectCity': 'Seleccionar ciudad',
    'home.selectLanguage': 'Seleccionar idioma',
    'home.allCities': 'Todas las ciudades',
    'home.virtualExploration': 'Exploración virtual',
    'home.virtualExplorationDesc': 'Explora lugares en el mapa',
    'home.places': 'Lugares',
    'home.placesDesc': 'Descubre todos los lugares',
    'home.blogTitle': 'Blog',
    'home.blogDesc': 'Artículos y guías',
    'home.travellerPath': 'Traveller.Path',
    'home.travellerPathDesc': 'Itinerarios personalizados',
    'home.travellerPathPending': 'Cuestionario pendiente',
    'home.finishSurvey': '¡Haz clic para terminar el cuestionario!',
    'home.whichCity': '¿Cuál será la próxima ciudad?',
    'home.stayTuned': 'Manténganse atentos, amigos',
    'home.workInProgress': 'En progreso',
    
    // Blog
    'blog.title': 'blog',
    'blog.subtitle': 'Guías, consejos e historias de viaje',
    'blog.writeArticle': 'Escribir artículo',
    'blog.searchArticles': 'Buscar artículos...',
    'blog.filters': 'Filtros',
    'blog.faq': 'FAQ',
    'blog.dayTrip': 'Excursión',
    'blog.tips': 'Consejos',
    'blog.faqTitle': 'Preguntas frecuentes',
    'blog.faqDesc': 'Respuestas a las preguntas más comunes sobre la plataforma',
    'blog.dayTripTitle': 'Itinerarios diarios',
    'blog.dayTripDesc': 'Descubre los mejores itinerarios para excursiones de un día',
    'blog.tipsTitle': 'Consejos de viaje',
    'blog.tipsDesc': 'Sugerencias útiles para mejorar tu experiencia de viaje',
    'blog.read': 'Leer',
    
    // Virtual Exploration
    'virtual.title': 'exploración virtual',
    'virtual.subtitle': 'Explora lugares en el mapa interactivo',
    'virtual.favorites': 'Tus lugares favoritos',
    'virtual.noFavorites': 'Aún no hay lugares favoritos.',
    'virtual.visit': 'Visitar',
    'virtual.googleMap': 'Google Map',
    'virtual.categories': 'Categorías',
    'virtual.all': 'Todas',
    'virtual.clearFilters': 'Limpiar filtros',
    'virtual.addPlace': 'Añadir lugar',
    'virtual.enlarge': 'Ampliar',
    'virtual.close': 'Cerrar',
    'virtual.noFavoritesDesc': 'Haz clic en el corazón en el mapa para añadir lugares a tus favoritos',
    'virtual.removeFavorite': 'Eliminar de favoritos',
    'virtual.exploreSubtitle': 'Explora lugares en el mapa y guarda tus favoritos',
    
    // Places (Luoghi)
    'places.title': 'Lugares',
    'places.subtitle': 'Descubre todos los lugares cuidadosamente seleccionados por nuestra guía',
    'places.approved': 'Explore Aprobado',
    'places.search': 'Buscar lugares...',
    'places.all': 'Todas',
    'places.noResults': 'No se encontraron lugares',
    'places.noResultsDesc': 'Intenta modificar los filtros de búsqueda',
    'places.loading': 'Cargando...',
    'places.cuisine': 'Tipo de cocina:',
    'places.meat': 'Carne',
    'places.fish': 'Pescado',
    'places.enter': 'Entrar',
    'places.maps': 'Maps',
    
    // Traveller Path
    'traveller.title': 'Traveller.Path',
    'traveller.subtitle': 'Crea tu itinerario personalizado',
    'traveller.backHome': 'Volver al inicio',
    'traveller.continuing': 'Estás continuando el cuestionario desde donde lo dejaste',
    'traveller.completed': 'preguntas completadas',
    'traveller.progress': 'Progreso',
    'traveller.previous': 'Anterior',
    'traveller.skip': 'Saltar',
    'traveller.next': 'Siguiente',
    'traveller.complete': 'Completar',
    'traveller.completedMessage': '¡Cuestionario completado! Tus datos han sido guardados.',
    'traveller.loading': 'Cargando...',
    
    // Questions
    'question.profileType': '¿Eres un Local o un Viajero?',
    'question.gender': 'Género',
    'question.age': 'Edad',
    'question.nationality': 'Nacionalidad',
    'question.travelComposition': 'Composición',
    'question.travelInclination': 'Inclinación',
    'question.duration': 'Duración de la estancia',
    'question.transport': 'Medio de transporte',
    'question.cuisine': 'Preferencias culinarias',
    'question.accommodationZone': 'Zona de alojamiento',
    'question.accessibility': 'Necesidades específicas',
    
    // Categories
    'category.profile': 'Perfil',
    'category.travelComposition': 'Composición del viaje',
    'category.travel': 'Viaje',
    'category.cuisine': 'Cocina / preferencias culinarias',
    'category.accommodation': 'Alojamiento',
    'category.accessibility': 'Accesibilidad / categorías frágiles',
    
    // Options
    'option.local': 'Local',
    'option.traveler': 'Viajero',
    'option.male': 'Masculino',
    'option.female': 'Femenino',
    'option.other': 'Otro',
    'option.under18': '<18',
    'option.18-24': '18–24',
    'option.25-34': '25–34',
    'option.35-49': '35–49',
    'option.50-64': '50–64',
    'option.over65': '>65',
    'option.europe': 'Europa',
    'option.usa': 'USA',
    'option.southAmerica': 'Sudamérica',
    'option.asia': 'Asia',
    'option.africa': 'África',
    'option.solo': 'Solo',
    'option.couple': 'Pareja',
    'option.group': 'Grupo',
    'option.family': 'Familia',
    'option.adventure': 'Aventura',
    'option.relax': 'Relajación',
    'option.culture': 'Cultura',
    'option.shopping': 'Compras',
    'option.nightlife': 'Vida nocturna',
    'option.socializing': 'Socialización',
    'option.1day': '1 día',
    'option.2days': '2 días',
    'option.3-7days': '3–7 días',
    'option.over7days': '>7 días',
    'option.own': 'Propio',
    'option.none': 'No',
    'option.rental': 'Quisiera alquilar',
    'option.homemade': 'Casero',
    'option.fineDining': 'Alta cocina',
    'option.healthy': 'Saludable',
    'option.winePairing': 'Maridaje de vinos',
    'option.streetFood': 'Comida callejera',
    'option.organic': 'Orgánico',
    'option.dairyFree': 'Sin lácteos',
    'option.halal': 'Halal',
    'option.nutsFree': 'Sin frutos secos',
    'option.glutenFree': 'Sin gluten',
    'option.vegan': 'Vegano',
    'option.vegetarian': 'Vegetariano',
    'option.z1': 'Z1',
    'option.z2': 'Z2',
    'option.z3': 'Z3',
    'option.z4': 'Z4',
    'option.z5': 'Z5',
    'option.reducedMobility': 'Movilidad reducida',
    'option.elderly': 'Personas mayores',
    'option.pregnant': 'Mujeres embarazadas',
    'option.odorophobia': 'Odorofobia',
    'option.mentalWellness': 'Bienestar mental'
  }
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('it');

  // Load language from localStorage on mount
  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage && translations[savedLanguage]) {
      setLanguage(savedLanguage);
    }
  }, []);

  // Save language to localStorage when it changes
  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}